CREATE TABLE `database_payroll`.`HOLIDAY` (
  `ID_HOLIDAY` INT NOT NULL AUTO_INCREMENT,
  `Holiday` VARCHAR(60) NOT NULL,
  `DateDay` DATE NOT NULL,
  `Status` VARCHAR(15) NOT NULL,
  `AddDate` DATE NOT NULL,
  `AlterDate` DATE NULL,
  `LowDate` DATE NULL,
  `FK_USER_ADD` INT NOT NULL,
  `FK_USER_ALTER` INT NULL,
  `FK_USER_LOW` INT NULL,
  PRIMARY KEY (`ID_HOLIDAY`),
  INDEX `FK_USER_ADD_idx` (`FK_USER_ADD` ASC) VISIBLE,
  INDEX `FK_USER_ALTER_idx` (`FK_USER_ALTER` ASC) VISIBLE,
  INDEX `FK_USER_LOW_idx` (`FK_USER_LOW` ASC) VISIBLE,
  CONSTRAINT `FK_HOLIDAY_USER_ADD`
    FOREIGN KEY (`FK_USER_ADD`)
    REFERENCES `database_payroll`.`USER` (`ID_USER`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_HOLIDAY_USER_ALTER`
    FOREIGN KEY (`FK_USER_ALTER`)
    REFERENCES `database_payroll`.`USER` (`ID_USER`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_HOLIDAY_USER_LOW`
    FOREIGN KEY (`FK_USER_LOW`)
    REFERENCES `database_payroll`.`USER` (`ID_USER`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

ALTER TABLE `database_payroll`.`HOLIDAY` 
COLLATE = utf8mb4_general_ci ;
