CREATE TABLE `database_payroll`.`PERSONAL` (
  `ID_PERSONAL` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(35) NOT NULL,
  `Surname` VARCHAR(35) NOT NULL,
  `IdentityCard` VARCHAR(25) NOT NULL,
  `TypeCard` VARCHAR(25) NOT NULL,
  `PhoneNumber` VARCHAR(25) NOT NULL,
  `WorkArea` VARCHAR(50) NOT NULL,
  `Job` VARCHAR(80) NOT NULL,
  `Salary` DECIMAL(9,2) NOT NULL,
  `FK_REGIMENT` INT NOT NULL,
  `FK_WORKINGDAY` INT NOT NULL,
  `TimeControl` CHAR(1) NOT NULL,
  `FK_CONTRACT` INT NOT NULL,
  `StartContract` DATE NOT NULL,
  `EndContract` DATE NULL,
  `FK_PAYACCOUNT` INT NOT NULL,
  `BankAccount` VARCHAR(30) NOT NULL,
  `Status` VARCHAR(15) NOT NULL,
  `AddedDate` DATE NOT NULL,
  `AlterDate` DATE NULL,
  `LowDate` DATE NULL,
  `FK_USER_ADD` INT NOT NULL,
  `FK_USER_ALTER` INT NULL,
  `FK_USER_LOW` INT NULL,
  PRIMARY KEY (`ID_PERSONAL`),
  INDEX `FK_REGIMENT_idx` (`FK_REGIMENT` ASC) VISIBLE,
  INDEX `FK_WORKINGDAY_idx` (`FK_WORKINGDAY` ASC) VISIBLE,
  INDEX `FK_CONTRACT_idx` (`FK_CONTRACT` ASC) VISIBLE,
  INDEX `FK_PAYACCOUNT_idx` (`FK_PAYACCOUNT` ASC) VISIBLE,
  INDEX `FK_USER_ADD_idx` (`FK_USER_ADD` ASC) VISIBLE,
  INDEX `FK_USER_ALTER_idx` (`FK_USER_ALTER` ASC) VISIBLE,
  INDEX `FK_USER_LOW_idx` (`FK_USER_LOW` ASC) VISIBLE,
  CONSTRAINT `FK_PERSONAL_REGIMENT`
    FOREIGN KEY (`FK_REGIMENT`)
    REFERENCES `database_payroll`.`REGIMENT` (`ID_REGIMENT`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_PERSONAL_WORKINGDAY`
    FOREIGN KEY (`FK_WORKINGDAY`)
    REFERENCES `database_payroll`.`WORKINGDAY` (`ID_WORKINGDAY`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_PERSONAL_CONTRACT`
    FOREIGN KEY (`FK_CONTRACT`)
    REFERENCES `database_payroll`.`CONTRACT` (`ID_CONTRACT`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_PERSONAL_PAYACCOUNT`
    FOREIGN KEY (`FK_PAYACCOUNT`)
    REFERENCES `database_payroll`.`PAYACCOUNT` (`ID_PAYACCOUNT`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_PERSONAL_USER_ADD`
    FOREIGN KEY (`FK_USER_ADD`)
    REFERENCES `database_payroll`.`USER` (`ID_USER`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_PERSONAL_USER_ALTER`
    FOREIGN KEY (`FK_USER_ALTER`)
    REFERENCES `database_payroll`.`USER` (`ID_USER`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_PERSONAL_USER_LOW`
    FOREIGN KEY (`FK_USER_LOW`)
    REFERENCES `database_payroll`.`USER` (`ID_USER`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

ALTER TABLE `database_payroll`.`PERSONAL` 
COLLATE = utf8mb4_general_ci ;


