CREATE TABLE `database_payroll`.`PERSONAL` (
  `ID_PERSONAL` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(35) NOT NULL,
  `Surname` VARCHAR(35) NOT NULL,
  `IdentityCard` VARCHAR(25) NOT NULL,
  `TypeCard` VARCHAR(25) NOT NULL,
  `PhoneNumber` VARCHAR(25) NOT NULL,
  `WorkArea` VARCHAR(50) NOT NULL,
  `Job` VARCHAR(80) NOT NULL,
  `Salary` DECIMAL(9,2) NOT NULL,
  `Regiment` VARCHAR(25) NOT NULL,
  `WorkingDay` VARCHAR(25) NOT NULL,
  `TimeControl` CHAR(1) NOT NULL,
  `Contract` VARCHAR(30) NOT NULL,
  `StartContract` DATE NOT NULL,
  `EndContract` DATE NOT NULL,
  `CashTransfer` VARCHAR(10) NOT NULL,
  `BankAccount` VARCHAR(30) NOT NULL,
  `Status` VARCHAR(15) NOT NULL,
  `AddedDate` DATE NOT NULL,
  `AlterDate` DATE NULL,
  `LowDate` DATE NULL,
  `FK_USER_ADD` INT NOT NULL,
  `FK_USER_ALTER` INT NOT NULL,
  `FK_USER_LOW` INT NOT NULL,
  PRIMARY KEY (`ID_PERSONAL`),
  INDEX `FK_ID_USER_ADD_idx` (`FK_USER_ADD` ASC) VISIBLE,
  CONSTRAINT `FK_ID_USER_ADD`
    FOREIGN KEY (`FK_USER_ADD`)
    REFERENCES `database_payroll`.`USER` (`ID_USER`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `database_payroll`.`PERSONAL` 
ADD INDEX `FK_ID_USER_ALTER_idx` (`FK_USER_ALTER` ASC) VISIBLE,
ADD INDEX `FK_ID_USER_LOW_idx` (`FK_USER_LOW` ASC) VISIBLE;
;
ALTER TABLE `database_payroll`.`PERSONAL` 
ADD CONSTRAINT `FK_ID_USER_ALTER`
  FOREIGN KEY (`FK_USER_ALTER`)
  REFERENCES `database_payroll`.`USER` (`ID_USER`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT,
ADD CONSTRAINT `FK_ID_USER_LOW`
  FOREIGN KEY (`FK_USER_LOW`)
  REFERENCES `database_payroll`.`USER` (`ID_USER`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;


/* SELECT * FROM PERSONAL;
ALTER TABLE PERSONAL RENAME COLUMN CancelDate TO LowDate;
ALTER TABLE PERSONAL CHANGE CancelDate LowDate DATE NOT NULL; */